### ISSUE TITLE
Hidden files not copied

### ISSUE THREAD

**Issue by jgall** [liatrio/pipeline-developer#8]
https://github.com/liatrio/pipeline-developer/blob/4be3cb0a77cb7bfbcf8be7c6a7cf251fe40af8bb/createDevJob.groovy#L10

https://github.com/liatrio/pipeline-developer/blob/4be3cb0a77cb7bfbcf8be7c6a7cf251fe40af8bb/jenkins/jobs/pipeline-updater/config.xml#L28

        cp -r * /var/jenkins_home/jobs/devPipeline/workspace/
 
should be:

        cp -r . /var/jenkins_home/jobs/devPipeline/workspace/

**Comment by jgall** [comment]
I'll make a PR whenever I find the time:)

**Comment by stein321** [comment]
hey @jgall what situation would you want a hidden file used in a repo? if it's something to do with authentication, it should really be stored within jenkins' credential provider right?

**Comment by jgall** [comment]
your git information is all in the .git directory. If you're making a pipeline that uses "when" you'll really want all that stuff around.

**Comment by stein321** [comment]
that's fair. I actually haven't tried this with multi-branch pipelines.
